Repository bloom-works/guides-template, pull requests merged in 2023-07, with the labels that each got.

#41 Node tests setup
  .github/workflows/pull_request.yml
  .gitignore
  Dockerfile
  README.md
  ci/tests.sh
  package.json
  playwright.config.js
  tests-examples/demo-todo-app.spec.js
  tests/example.spec.js
Labels: release-patch

#34 Add Table of Contents component
  .eleventy.js
  _includes/components/TableOfContents.js
  _includes/css/base/layout.css
  _includes/css/base/typography.css
  _includes/css/components/toc.css
  _includes/layouts/content.njk
  components/toc.md
  package.json
  theme.njk
Labels: release-major

#48 Modified JS Linter to include eleventy config file
  .eleventy.js
  .eslintrc.js
Labels: release-minor

#45 Add ESLinter for JS Linting
  .eleventy.js
  .eslintrc.js
  README.md
  _includes/components/Grid.js
  _includes/components/GridColumn.js
  _includes/components/PageHeader.js
  _includes/components/Pagination.js
  _includes/components/ResourceGroup.js
  _includes/components/ResourcePrivate.js
  _includes/components/ResourcePublic.js
  _includes/components/TableOfContents.js
  ci/linter.sh
  markdown.js
  package.json
  playwright.config.js
  tests-examples/demo-todo-app.spec.js
Labels: release-minor

#30 Add Checklist and Key Questions components
  .eleventy.js
  _includes/components/Checklist.js
  _includes/components/KeyQuestions.js
  _includes/css/base/layout.css
  _includes/css/base/root.css
  _includes/css/components/icon-list.css
  components/checklist.md
  components/key-questions.md
  theme.njk
Labels: release-minor

#51 Delete merged conflicts from theme.njk
  theme.njk
Labels: release-patch

#31 Add Callout components
  .eleventy.js
  _includes/components/Callout.js
  _includes/css/components/callout.css
  _includes/icon-paths/calendar-week.svg
  _includes/icon-paths/exclamation.svg
  _includes/icon-paths/heart.svg
  _includes/icon-paths/lightbulb.svg
  components/callout.md
  theme.njk
Labels: release-minor

#37 Small typography fixes
  _includes/css/base/root.css
  _includes/css/base/typography.css
  index.njk
Labels: release-patch

#38 Add Private Link component
  .eleventy.js
  _includes/components/PrivateLink.js
  _includes/css/components/private-link.css
  components/private-link.md
  theme.njk
Labels: release-minor

#46 Add CSS Linter
  .stylelintrc.json
  README.md
  _includes/css/base/base.css
  _includes/css/base/layout.css
  _includes/css/base/normalize.css
  _includes/css/base/root.css
  _includes/css/base/typography.css
  _includes/css/components/button.css
  _includes/css/components/callout.css
  _includes/css/components/footer.css
  _includes/css/components/pagination.css
  _includes/css/components/resources.css
  _includes/css/components/tables.css
  _includes/css/components/toc.css
  ci/linter.sh
  package.json
Labels: release-minor

#47 Add Nunjucks Linter
  Dockerfile
  README.md
  _includes/layouts/css.njk
  _includes/layouts/footer.njk
  _includes/layouts/head.njk
  _includes/layouts/post.njk
  _includes/layouts/seo.njk
  _includes/postslist.njk
  ci/linter.sh
Labels: release-minor

#52 Set up Accessibility testing
  .eslintrc.js
  .github/workflows/pull_request.yml
  Dockerfile
  README.md
  ci/tests.sh
  cypress.config.js
  cypress/e2e/spec.cy.js
  cypress/support/e2e.js
  package.json
Labels: release-minor

#35 Add Site Navigation component
  _includes/bloom-logo-graphic.svg
  _includes/css/components/navigation.css
  _includes/icon-paths/book.svg
  _includes/icon-paths/search.svg
  _includes/icon-paths/x-circle.svg
  _includes/layouts/base.njk
  _includes/layouts/navigation.njk
  components/site-navigation.md
  index.njk
  theme.njk
Labels: release-major

#54 Create pull_request_template.md
  .github/pull_request_template.md
  _includes/layouts/navigation.njk
Labels: release-minor

#55 All components page created for accessibility testing
  .github/pull_request_template.md
  components/all-components.md
  cypress/e2e/spec.cy.js
Labels: release-minor
